#!/usr/bin/env bash
set -euo pipefail
ROOT="/apdcephfs_gy2/share_303214315/cedricnie/develop/training-free"; PF="$ROOT/third_party/Pyramid-Forcing/configs/pyramid-forcing.yaml"; PROMPTS="$ROOT/prompts/review_3_prompts.txt"
run(){ local gpu=$1 id=$2 tag=$3; shift 3; env CUDA_VISIBLE_DEVICES=$gpu PROMPTS="$PROMPTS" FRAMES=120 SEED=0 STRENGTH=0 GATE_LAMBDA=0 RECENT_FRAMES=21 METHOD_TAG=$tag RUN_ID=$id "$@" bash "$ROOT/scripts/run_v35_pf_value_refresh.sh"; }
COMMON=(CONFIG_PATH="$PF" STRUCTURED_MEMORY_ENABLE=1 MEMORY_STORAGE_MODE=archive MEMORY_ARCHIVE_MAX_FRAMES=24 MEMORY_ARCHIVE_POLICY=coverage MEMORY_TOP_K_FRAMES=3 MEMORY_RECENT_EXCLUDE_FRAMES=4 MEMORY_SELECTION_POLICY=query MEMORY_FUSION_MODE=convex MEMORY_READOUT_MODE=all MEMORY_GATE=0.05 MEMORY_CONFIDENCE=0.25 MEMORY_TEMPERATURE=0.3 MEMORY_LAYER_START=15 MEMORY_LAYER_END=21 MEMORY_WARMUP_BLOCKS=6 MEMORY_HEAD_ROUTING=static MEMORY_HEAD_LABELS="" MEMORY_CONTROL_MODE=normal)
run 4 20260720_v54_raw raw "${COMMON[@]}" MEMORY_POSITION_MODE=none MEMORY_MIN_RETRIEVAL_MARGIN=0.0 &
run 5 20260720_v54_local_rope local_rope "${COMMON[@]}" MEMORY_POSITION_MODE=local_grid MEMORY_MIN_RETRIEVAL_MARGIN=0.0 &
run 6 20260720_v54_local_m03 local_m03 "${COMMON[@]}" MEMORY_POSITION_MODE=local_grid MEMORY_MIN_RETRIEVAL_MARGIN=0.03 &
run 7 20260720_v54_local_m05 local_m05 "${COMMON[@]}" MEMORY_POSITION_MODE=local_grid MEMORY_MIN_RETRIEVAL_MARGIN=0.05 &
status=0; for p in $(jobs -p); do wait "$p" || status=1; done; exit $status
