batch_size: 1
beta1: 0.0
beta1_critic: 0.0
beta2: 0.999
beta2_critic: 0.999
causal: true
ckpt_step: 0
compile_ffn: false
context_noise: 0
data_path: prompts/vidprom_filtered_extended.txt
denoising_loss_type: flow
denoising_step_list:
- 1000
- 750
- 500
- 250
dfake_gen_update_ratio: 5
discriminator_lr_multiplier: 1.0
distribution_loss: dmd
ema_start_step: 200
ema_weight: 0.99
eval_first_n: 64
fake_score_fsdp_wrap_strategy: size
few_step_cfg_enabled: false
gc_interval: 100
generator_ckpt: checkpoints/ode_init.pt
generator_fsdp_wrap_strategy: size
gradient_checkpointing: true
guidance_scale: 3.0
height: 480
i2v: false
image_or_video_shape:
- 1
- 21
- 16
- 60
- 104
independent_first_frame: false
last_step_only: false
load_raw_video: false
log_iters: 50
lr: 2.0e-06
lr_critic: 4.0e-07
mixed_precision: true
model_kwargs:
  local_attn_size: 21
  sink_size: 0
  timestep_shift: 5.0
negative_prompt: "\u8272\u8C03\u8273\u4E3D\uFF0C\u8FC7\u66DD\uFF0C\u9759\u6001\uFF0C\
  \u7EC6\u8282\u6A21\u7CCA\u4E0D\u6E05\uFF0C\u5B57\u5E55\uFF0C\u98CE\u683C\uFF0C\u4F5C\
  \u54C1\uFF0C\u753B\u4F5C\uFF0C\u753B\u9762\uFF0C\u9759\u6B62\uFF0C\u6574\u4F53\u53D1\
  \u7070\uFF0C\u6700\u5DEE\u8D28\u91CF\uFF0C\u4F4E\u8D28\u91CF\uFF0CJPEG\u538B\u7F29\
  \u6B8B\u7559\uFF0C\u4E11\u964B\u7684\uFF0C\u6B8B\u7F3A\u7684\uFF0C\u591A\u4F59\u7684\
  \u624B\u6307\uFF0C\u753B\u5F97\u4E0D\u597D\u7684\u624B\u90E8\uFF0C\u753B\u5F97\u4E0D\
  \u597D\u7684\u8138\u90E8\uFF0C\u7578\u5F62\u7684\uFF0C\u6BC1\u5BB9\u7684\uFF0C\u5F62\
  \u6001\u7578\u5F62\u7684\u80A2\u4F53\uFF0C\u624B\u6307\u878D\u5408\uFF0C\u9759\u6B62\
  \u4E0D\u52A8\u7684\u753B\u9762\uFF0C\u6742\u4E71\u7684\u80CC\u666F\uFF0C\u4E09\u6761\
  \u817F\uFF0C\u80CC\u666F\u4EBA\u5F88\u591A\uFF0C\u5012\u7740\u8D70"
num_frame_per_block: 3
num_frames: 81
num_samples: 1
num_train_timestep: 1000
num_training_frames: 21
prompt_name: MovieGenVideoBench
prompt_path: prompts/MovieGenVideoBench.txt
real_name: Wan2.1-T2V-14B
real_score_fsdp_wrap_strategy: size
same_step_across_blocks: true
seed: 0
sharding_strategy: hybrid_full
text_encoder_fsdp_wrap_strategy: size
timestep_shift: 5.0
total_batch_size: 64
trainer: score_distillation
ts_schedule: false
use_pyramidkv: false
use_teacache: false
vae_decode_mode: batch
wandb_entity: WANDB_ENTITY
wandb_host: WANDB_HOST
wandb_key: WANDB_KEY
wandb_project: WANDB_PROJECT
warp_denoising_step: true
weight_decay: 0.01
width: 832
